"""Build BC Supreme Court templates from the headless XFA flatten.

Source: xfa/sc_out/<docId>.pdf (pdf.js XFA render printed by Chrome) plus
<docId>.fields.json (the government's own field boxes, read off the rendered DOM
in PDF points). Only the forms whose blank layout *is* the filing document are
built here; the Adobe interview/"Preview"-driven ones are excluded by name.

Run: python3 build_bc_supreme.py [--promote]
"""
import json
import os
import shutil
import sys

import fitz

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import bc_pipeline as bp  # noqa: E402

EXPORT = "/Users/lorelaiphinnemore/Documents/CloudAct/Frontend /Calculator-code/auth-server/form-template-export"
STAGE = os.path.join(EXPORT, "_incoming_bc")
SC = os.path.join(os.path.dirname(os.path.abspath(__file__)), "xfa", "sc_out")
OUT = os.path.join(STAGE, "out")
QA = os.path.join(STAGE, "qa")

# Adobe interview forms: the blank layout is a data-entry wizard whose filed
# document is generated by script at Preview time, so flattening the blank form
# produces the wrong document. Sourced separately from BC Laws Appendix A.
INTERVIEW = {"BCSC_F1_1", "BCSC_F1_2", "BCSC_F3", "BCSC_F4", "BCSC_F5", "BCSC_F6",
             "BCSC_F31", "BCSC_F38", "BCSC_F45", "BCSC_F51", "BCSC_F51_1", "BCSC_F52"}

FORMS = [
    ("BCSC_F8", "F8", "Financial statement", "Supreme Court – Financial"),
    ("BCSC_F10", "F10", "Notice of address for service", "Supreme Court – Notices"),
    ("BCSC_F17", "F17", "Requisition - general", "Supreme Court – Requisitions"),
    ("BCSC_F19", "F19", "Notice of judicial case conference", "Supreme Court – Conferences"),
    ("BCSC_F19_2", "F19.2", "Notice of case planning conference", "Supreme Court – Conferences"),
    ("BCSC_F20", "F20", "List of documents", "Supreme Court – Discovery"),
    ("BCSC_F21", "F21", "Appointment to examine for discovery", "Supreme Court – Discovery"),
    ("BCSC_F30", "F30", "Affidavit", "Supreme Court – Evidence"),
    ("BCSC_F32", "F32", "Application response", "Supreme Court – Applications"),
    ("BCSC_F33", "F33", "Consent order", "Supreme Court – Orders"),
    ("BCSC_F34", "F34", "Order made without notice", "Supreme Court – Orders"),
    ("BCSC_F43", "F43", "Notice to cross-examine", "Supreme Court – Notices"),
    ("BCSC_F46", "F46", "Trial certificate", "Supreme Court – Trial"),
    ("BCSC_F51_2", "F51.2", "Order made at trial management conference", "Supreme Court – Orders"),
    ("BCSC_F55", "F55", "Appointment", "Supreme Court – Requisitions"),
    ("BCSC_F56", "F56", "Certificate of divorce", "Supreme Court – Divorce"),
    ("BCSC_F75", "F75", "Notice of hearing", "Supreme Court – Notices"),
    ("BCSC_F89", "F89", "Notice of intention to withdraw as lawyer", "Supreme Court – Representation"),
    ("BCSC_F91", "F91", "Notice of withdrawal of lawyer", "Supreme Court – Representation"),
    ("BCSC_F96", "F96", "Electronic filing statement", "Supreme Court – Filing"),
]

CATEGORY_ORDER = [
    "Supreme Court – Applications",
    "Supreme Court – Financial",
    "Supreme Court – Orders",
    "Supreme Court – Evidence",
    "Supreme Court – Discovery",
    "Supreme Court – Conferences",
    "Supreme Court – Trial",
    "Supreme Court – Divorce",
    "Supreme Court – Notices",
    "Supreme Court – Representation",
    "Supreme Court – Requisitions",
    "Supreme Court – Filing",
]

TYPE_BY_TAG = {"textarea": "TextArea", "select": "TextField"}


def overlay_fields(doc_id, raw, page_sizes, pdf_path):
    """XFA field boxes -> overlay fields, dropping signature boxes (gate D)."""
    doc = fitz.open(pdf_path)
    captions = {n: bp.signature_captions(doc[n - 1]) for n in range(1, doc.page_count + 1)}
    doc.close()

    fields, skipped, baked = [], [], []
    index = 0
    for item in raw:
        if item["inputType"] in ("checkbox", "radio"):
            kind = "CheckBox"
        else:
            kind = TYPE_BY_TAG.get(item["tag"], "TextField")
        # The flatten printed this field's default into the background ("Claimant",
        # "1st affidavit", a paragraph number). An editable box over it would let a
        # lawyer type text that collides with the printed default, so the default
        # stands as printed and no box goes on top.
        if kind != "CheckBox" and item.get("printedValue"):
            baked.append({"page": item["page"], "value": item["printedValue"][:40]})
            continue
        rect = fitz.Rect(item["x"], item["y"], item["x"] + item["width"], item["y"] + item["height"])
        if kind != "CheckBox" and bp.is_signature_box(rect, item.get("name"), captions.get(item["page"], [])):
            skipped.append({"page": item["page"], "name": item.get("name", ""), "why": "signature"})
            continue
        index += 1
        fields.append({
            "id": bp.new_id(doc_id, index),
            "type": kind,
            "x": round(item["x"], 2),
            "y": round(item["y"], 2),
            "width": round(item["width"] * bp.SCALE, 2),
            "height": round(item["height"] * bp.SCALE, 2),
            "value": "",
            "fontSize": 9,
            "color": [0, 0, 0],
            "background": "none",
            "border": "none",
            "page": item["page"],
        })
    return fields, skipped, baked


def footer_text(pdf_path):
    """The government's edition stamp, e.g. 'Last updated: January 6, 2026'."""
    doc = fitz.open(pdf_path)
    for line in doc[0].get_text().splitlines():
        if line.strip().lower().startswith("last updated"):
            doc.close()
            return line.strip()[:120]
    doc.close()
    return None


def main():
    promote = "--promote" in sys.argv
    os.makedirs(OUT, exist_ok=True)
    os.makedirs(QA, exist_ok=True)

    rows, audits, failures = [], [], []
    for doc_id, form_no, name, category in FORMS:
        assert doc_id not in INTERVIEW, doc_id
        source = os.path.join(SC, "%s.pdf" % doc_id)
        background = os.path.join(OUT, "%s.pdf" % doc_id)
        shutil.copy(source, background)

        doc = fitz.open(background)
        page_sizes = [[round(p.rect.width, 1), round(p.rect.height, 1)] for p in doc]
        widgets = sum(len(list(p.widgets())) for p in doc)
        pages = doc.page_count
        doc.close()
        if widgets:
            failures.append((doc_id, "flatten left %d widgets" % widgets))

        raw = json.load(open(os.path.join(SC, "%s.fields.json" % doc_id)))
        fields, skipped, baked = overlay_fields(doc_id, raw, page_sizes, background)
        bp.clamp_to_page(fields, page_sizes)
        nudged = bp.nudge_off_hint(background, fields)
        snapped, missed = bp.snap_checkboxes(background, fields)
        bp.assign_marks(background, fields)
        bp.stamp_shapes(background, fields)
        bp.snap_text_fields(background, fields)
        bp.expand_ruled_blocks(fields, background)
        bp.clear_printed_labels(background, fields)
        bp.merge_sliver_fields(background, fields)
        bp.size_amounts_to_dollar(background, fields)
        geometry = bp.check_geometry(fields, page_sizes)
        overlaps = bp.check_overlap(background, fields)
        bp.qa_render(background, fields, os.path.join(QA, "%s_qa.pdf" % doc_id))
        bp.write_mapping(os.path.join(OUT, "%s.json" % doc_id), fields)

        audits.append({"docId": doc_id, "pages": pages, "fields": len(fields),
                       "checkboxes": sum(1 for f in fields if f["type"] == "CheckBox"),
                       "signaturesSkipped": len(skipped), "signatureDetail": skipped,
                       "printedDefaults": len(baked), "printedDefaultDetail": baked,
                       "geometryProblems": geometry, "overlapFlags": len(overlaps),
                       "overlapDetail": overlaps[:20], "nativeWidgets": widgets})
        if geometry:
            failures.append((doc_id, "geometry", geometry[:3]))

        rows.append({
            "title": "Form %s - %s" % (form_no, name),
            "shortTitle": "BC SC Form %s" % form_no,
            "footerText": footer_text(background),
            "status": "active",
            "fileName": "%s.pdf" % doc_id,
            "docId": doc_id,
            "province": "BC",
            "category": category,
            "version": 1,
            "pageCount": pages,
            "_sortKey": (CATEGORY_ORDER.index(category), float(form_no[1:])),
        })
        print("%-12s pages=%-3d fields=%-4d cb=%-4d sig-skipped=%-3d geom=%-2d overlap=%d"
              % (doc_id, pages, len(fields), audits[-1]["checkboxes"], len(skipped),
                 len(geometry), len(overlaps)) + "  baked=%d" % len(baked))

    rows.sort(key=lambda r: r["_sortKey"])
    for row in rows:
        del row["_sortKey"]
    with open(os.path.join(OUT, "bc_sc_rows.json"), "w") as fh:
        json.dump(rows, fh, indent=1)
    with open(os.path.join(OUT, "bc_sc_audit.json"), "w") as fh:
        json.dump(audits, fh, indent=1)

    print("\nfailures: %s" % (failures or "none"))
    print("total fields: %d across %d forms" % (sum(a["fields"] for a in audits), len(audits)))
    if promote and not failures:
        for row in rows:
            doc_id = row["docId"]
            shutil.copy(os.path.join(OUT, "%s.pdf" % doc_id), os.path.join(EXPORT, "%s.pdf" % doc_id))
            shutil.copy(os.path.join(OUT, "%s.json" % doc_id), os.path.join(EXPORT, "%s.json" % doc_id))
        print("promoted %d templates into form-template-export/" % len(rows))


if __name__ == "__main__":
    main()
